import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/home.module.scss'
import ColorDisplay from './components/color-display'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Rong App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ColorDisplay />
      </main>
    </>
  )
}

export default Home
